UDID: "DDAC13B0-786D-4DC7-A920-4BEAF56CD616"
BUNDLEID: "com.iOS.Demo"
TIMING: "1"
PORT: "3460"
PROXYPORT: "5680"
NeedScreenshot: "true"
ScreenshotFolder: "/Users/xinxi/Desktop/iOSMonkey/pic"
VERBOSE: "true"
TRACEPATH: "/Users/xinxi/Desktop/iOSMonkey"
AppiumLogFolder: "/Users/xinxi/Desktop/iOSMonkey"
TestCase: "/Users/xinxi/Desktop/iOSMonkey/testcase.yaml"