UDID: "606EC265-1ED8-454D-AF80-BEB78A417B55"
BUNDLEID: "com.iOS.Demo"
TIMING: "1"
PORT: "3460"
PROXYPORT: "5680"
NeedScreenshot: "true"
ScreenshotFolder: "/Users/xinxi/Desktop/iOSMonkey"
VERBOSE: "true"
TRACEPATH: "/Users/xinxi/Desktop/iOSMonkey"
AppiumLogFolder: "/Users/xinxi/Desktop/iOSMonkey"
